FROM golang:1.22.5-alpine3.20 AS builder

WORKDIR /app

COPY . .
RUN go mod download
RUN go build -o cli cmd/cli/main.go

FROM alpine:3.20

WORKDIR /root

ENV TERM=xterm-256color

COPY --from=builder /app/cli .
COPY --from=builder /app/cli.yaml .

CMD ["./cli"]