FROM golang:1.22.5-alpine3.20 AS builder

WORKDIR /app

COPY . .
RUN go mod download
RUN go build -o api cmd/api/main.go

FROM alpine:3.20

WORKDIR /root

COPY --from=builder /app/api ./
COPY --from=builder /app/api.yaml ./

CMD ["./api"]